### ISSUE TITLE
Release: Relivator v0.0.0-v1.0.0

### ISSUE THREAD

**Issue by blefnk** [blefnk/relivator#1]
## Project Features | Detailed Roadmap for **v1.0.0** Release

This roadmap is crafted to give you a comprehensive view of the features and improvements we are committed to delivering in this Next.js starter project. If you spot any inaccuracies, we highly encourage you to notify us [on the special discussions page](https://github.com/blefnk/relivator/discussions/6).

### Core Technologies

- [x] **Framework & Language Stack**: Utilizes [**Next.js 13**](https://nextjs.org), [**React 18**](https://react.dev), and [**TypeScript 5**](https://typescriptlang.org) as the foundational stack.
- [x] **Authentication**: Managed via [**NextAuth**](https://authjs.dev).

### Configuration and Middleware

- [x] **Optimized Configuration**: Fine-tuned `next.config.mjs` file supports nested configurations for a modular approach.
- [x] **Middleware Configuration**: A well-annotated `middleware.ts` for internationalization (i18n) and authentication using next-auth.

### Internationalization

- [x] **Robust i18n Support**: Comprehensive internationalization capabilities, initially using [**next-intl**](https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components) and [**next-international**](https://github.com/QuiiBz/next-international). Future plans involve proprietary solutions.

### Data Handling

- [x] **Data Fetching**: Server and client-side data fetching enabled through [**tRPC**](https://trpc.io) & [**TanStack Query**](https://tanstack.com/query).

### Development Experience

- [x] **VSCode Settings**: Customized Visual Studio Code settings along with a list of recommended extensions for a smooth development experience.
  
### UI/UX Features

- [x] **UI Design**: Utilizes a carefully crafted, aesthetically pleasing user interface.
- [x] **UI Components**: Leveraging [**Radix**](https://radix-ui.com) and additional libraries such as [**shadcn/ui**](https://ui.shadcn.com) and [@auth/drizzle-adapter](https://authjs.dev/reference/adapter/drizzle) for enhanced UI components.

### E-commerce Features

- [x] **Storefront**: Fully functional storefront featuring categorized products and subcategories.
- [x] **Payment Integration**: Seamless customer checkout experience via **Stripe Checkout**.

### SEO and Content

- [x] **Metadata API**: Integrated [**Next.js Metadata API**](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) for effective SEO.
- [x] **Content Sharing**: Blogging platform backed by **MDX** for sharing insights and updates.

### Documentation and Code Quality

- [x] **Project Documentation**: An easy-to-understand `README.md` focuses on helping beginners get started, and includes explanations for all [**environment variables**](https://nextjs.org/docs/basic-features/environment-variables).
- [x] **Styling**: Uses [**TailwindCSS**](https://tailwindcss.com) for a utility-first CSS architecture.
  
### Code Quality

- [x] **Code Linting**: Utilizes [**EsLint**](https://eslint.org) integrated with [**Prettier**](https://prettier.io) for maintaining code quality.
  
### Backend and Database

- [x] **ORM and Kit**: Incorporates [**Drizzle ORM**](https://orm.drizzle.team) and [**DrizzleKit**](https://orm.drizzle.team/kit-docs/overview), optimized for serverless architectures like [**Neon**](https://neon.tech) and [**Vercel Postgres**](https://vercel.com/docs/storage/vercel-postgres).

### Payment and Subscription

- [x] **Subscription Handling**: Manages user subscriptions through Stripe.

### Input and Validation

- [x] **Input Validation**: Integrated **Zod** for robust form and data validation.

### Typography

- [x] **Font System**: Elegantly implemented typography using the [**Inter**](https://rsms.me/inter) font family among others.

By focusing on the granularity of each feature, this roadmap aims to provide a clear and actionable guide for project contributors and users alike.

**Comment by Trongar** [comment]
when is this going to be released? i'm waiting for it

**Comment by blefnk** [comment]
✅ [**v1.0.0 🎉 Relivator Release**](https://github.com/blefnk/relivator/releases/tag/1.0.0)
