### ISSUE TITLE
Move component styles to .css or .scss files

### ISSUE THREAD

**Issue by SolomidHero** [blefnk/relivator#18]
I found that code is not convinient for customizing. In most components styles are inside tag attributes.
I think it is better to move style definitions to other files (i.e. .scss), or use packages that provide syntax sugar for styles in .tsx files.

**Comment by blefnk** [comment]
Added to the project roadmap, thanks for the idea! Release 1.2.0 is almost here, so I'll try to move the component styles in the future 1.3.0-1.4.0 releases.
