### ISSUE TITLE
Migrate: Clerk → NextAuth.js

### ISSUE THREAD

**Issue by nerkn** [blefnk/relivator#7]
Nice project, I wanted to use but 10 years ago I made a community page and suddenly It exploded for that time, I got 20k users a day and I was hardly making 100$ from this. If I'd used clerk, I would need to pay for this nearly 1000$'s. Currently project I want to make cant reach free tier but I'd rather gamble 1k on lottery than this.

If you ever plan to move away from clerk, I want to fiddle

**Comment by blefnk** [comment]
@nerkn Hello! Thank you for your message and sharing your experience. I recently completed migrating from Clerk to NextAuth.js for Relivator v1. It seems everything is working well and stable, and I even managed to implement an account linking system. Besides, Relivator v1 will have a lot of exciting new features! I plan to release the 1.0.0 version by the end of the week. After that, I believe improvements to the authentication system will still be much needed. So, I would greatly appreciate any help you can offer.

**Comment by blefnk** [comment]
✅ Migration Completed in [**v1.0.0 🎉 Relivator Release**](https://github.com/blefnk/relivator/releases/tag/1.0.0)
